export const SET_LOCAL_STREAM = 'SET_LOCAL_STREAM';
export const SET_REMOTE_STREAM = 'SET_REMOTE_STREAM';
export const SET_CALL_STATE = 'SET_CALL_STATE';
export const CALL_SET_CHAT_MESSAGE = 'CALL_SET_CHAT_MESSAGE';