export const SET_LOCAL_STREAM = 'SET_LOCAL_STREAM';
export const SET_REMOTE_STREAM = 'SET_REMOTE_STREAM';
export const SET_CALL_STATE = 'SET_CALL_STATE';
export const SET_CHAT_MESSAGE = 'CALL_SET_CHAT_MESSAGE';
export const SET_CALLER_USERNAME = 'SET_CALLER_USERNAME';
export const SET_CALLING_DIALOG_VISIBLE = 'SET_CALLING_DIALOG_VISIBLE';
export const SET_SCREEN_SHARING_ACTIVE = 'SET_SCREEN_SHARING_ACTIVE';
export const RESET_CALL_DATA_STATE = 'RESET_CALL_DATA_STATE';