export const ADD_USERNAME = 'ADD_USERNAME';
export const ADD_SOCKETID = 'ADD_SOCKETID';
export const UPDATE_ACTIVE_USERS = 'UPDATE_ACTIVE_USERS';
export const CLEAR_ACTIVE_USERS = 'CLEAR_ACTIVE_USERS';
export const UPDATE_GROUP_CALL_ROOMS = 'UPDATE_GROUP_CALL_ROOMS';
export const CLEAR_GROUP_CALL_ROOMS = 'CLEAR_GROUP_CALL_ROOMS';